{% set name = "xcb-util-cursor" %}
{% set version = "0.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://xcb.freedesktop.org/dist/xcb-util-cursor-{{ version }}.tar.xz
  sha256: 28dcfe90bcab7b3561abe0dd58eb6832aa9cc77cfe42fcdfa4ebe20d605231fb

build:
  number: 2
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('xcb-util-cursor', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make
    - m4
    - pkg-config
  host:
    - libxcb >=1.13
    - xorg-xproto
    - xcb-util-renderutil
    - xcb-util-image
  run:
    - libxcb >=1.13

test:
  commands:
    - test -f ${PREFIX}/lib/libxcb-cursor.so

about:
  home: https://xcb.freedesktop.org/
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'port of Xlib libXcursor functions'

extra:
  recipe-maintainers:
    - n-elie 
